
import { BibleBook } from './types';

export const BIBLE_BOOKS: (BibleBook & { apiName: string })[] = [
  { name: "Gênesis", apiName: "Genesis", chapters: 50 },
  { name: "Êxodo", apiName: "Exodus", chapters: 40 },
  { name: "Levítico", apiName: "Leviticus", chapters: 27 },
  { name: "Números", apiName: "Numbers", chapters: 36 },
  { name: "Deuteronômio", apiName: "Deuteronomy", chapters: 34 },
  { name: "Josué", apiName: "Joshua", chapters: 24 },
  { name: "Juízes", apiName: "Judges", chapters: 21 },
  { name: "Rute", apiName: "Ruth", chapters: 4 },
  { name: "1 Samuel", apiName: "1 Samuel", chapters: 31 },
  { name: "2 Samuel", apiName: "2 Samuel", chapters: 24 },
  { name: "1 Reis", apiName: "1 Kings", chapters: 22 },
  { name: "2 Reis", apiName: "2 Kings", chapters: 25 },
  { name: "1 Crônicas", apiName: "1 Chronicles", chapters: 29 },
  { name: "2 Crônicas", apiName: "2 Chronicles", chapters: 36 },
  { name: "Esdras", apiName: "Ezra", chapters: 10 },
  { name: "Neemias", apiName: "Nehemiah", chapters: 13 },
  { name: "Ester", apiName: "Esther", chapters: 10 },
  { name: "Jó", apiName: "Job", chapters: 42 },
  { name: "Salmos", apiName: "Psalms", chapters: 150 },
  { name: "Provérbios", apiName: "Proverbs", chapters: 31 },
  { name: "Eclesiastes", apiName: "Ecclesiastes", chapters: 12 },
  { name: "Cânticos", apiName: "Song of Solomon", chapters: 8 },
  { name: "Isaías", apiName: "Isaiah", chapters: 66 },
  { name: "Jeremias", apiName: "Jeremiah", chapters: 52 },
  { name: "Lamentações", apiName: "Lamentations", chapters: 5 },
  { name: "Ezequiel", apiName: "Ezekiel", chapters: 48 },
  { name: "Daniel", apiName: "Daniel", chapters: 12 },
  { name: "Oséias", apiName: "Hosea", chapters: 14 },
  { name: "Joel", apiName: "Joel", chapters: 3 },
  { name: "Amós", apiName: "Amos", chapters: 9 },
  { name: "Obadias", apiName: "Obadiah", chapters: 1 },
  { name: "Jonas", apiName: "Jonah", chapters: 4 },
  { name: "Miquéias", apiName: "Micah", chapters: 7 },
  { name: "Naum", apiName: "Nahum", chapters: 3 },
  { name: "Habacuque", apiName: "Habakkuk", chapters: 3 },
  { name: "Sofonias", apiName: "Zephaniah", chapters: 3 },
  { name: "Ageu", apiName: "Haggai", chapters: 2 },
  { name: "Zacarias", apiName: "Zechariah", chapters: 14 },
  { name: "Malaquias", apiName: "Malachi", chapters: 4 },
  { name: "Mateus", apiName: "Matthew", chapters: 28 },
  { name: "Marcos", apiName: "Mark", chapters: 16 },
  { name: "Lucas", apiName: "Luke", chapters: 24 },
  { name: "João", apiName: "John", chapters: 21 },
  { name: "Atos", apiName: "Acts", chapters: 28 },
  { name: "Romanos", apiName: "Romans", chapters: 16 },
  { name: "1 Coríntios", apiName: "1 Corinthians", chapters: 16 },
  { name: "2 Coríntios", apiName: "2 Corinthians", chapters: 13 },
  { name: "Gálatas", apiName: "Galatians", chapters: 6 },
  { name: "Efésios", apiName: "Ephesians", chapters: 6 },
  { name: "Filipenses", apiName: "Philippians", chapters: 4 },
  { name: "Colossenses", apiName: "Colossians", chapters: 4 },
  { name: "1 Tessalonicenses", apiName: "1 Thessalonians", chapters: 5 },
  { name: "2 Tessalonicenses", apiName: "2 Thessalonians", chapters: 3 },
  { name: "1 Timóteo", apiName: "1 Timothy", chapters: 6 },
  { name: "2 Timóteo", apiName: "2 Timothy", chapters: 4 },
  { name: "Tito", apiName: "Titus", chapters: 3 },
  { name: "Filemom", apiName: "Philemon", chapters: 1 },
  { name: "Hebreus", apiName: "Hebrews", chapters: 13 },
  { name: "Tiago", apiName: "James", chapters: 5 },
  { name: "1 Pedro", apiName: "1 Peter", chapters: 5 },
  { name: "2 Pedro", apiName: "2 Peter", chapters: 3 },
  { name: "1 João", apiName: "1 John", chapters: 5 },
  { name: "2 João", apiName: "2 John", chapters: 1 },
  { name: "3 João", apiName: "3 John", chapters: 1 },
  { name: "Judas", apiName: "Jude", chapters: 1 },
  { name: "Apocalipse", apiName: "Revelation", chapters: 22 }
];
